const router = require('express').Router();
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { isAuthenticated } = require('../middleware/auth');
const { checkPlagiarism } = require('../VectorStore');
require('dotenv').config();

// Initialize Gemini AI Client
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Configuration for plagiarism detection
const PLAGIARISM_THRESHOLD = 0.85; // 85% similarity threshold

// System instruction for RP Application analysis
const SYSTEM_INSTRUCTION = `You are an RP Administrator for LS Reborn, a GTA V Roleplay server. Analyze the submitted roleplay application text and evaluate it based on the following criteria:

1. AI Probability (0-100): How likely is it that this text was generated by AI? Look for: generic phrasing, lack of personal voice, overly perfect grammar, templated responses, or unnaturally consistent tone.

2. Quality (0-100): Overall writing quality including grammar, punctuation, coherence, creativity, and storytelling ability.

3. Uniqueness (0-100): How original and creative is the content? Does it avoid clichés and generic backstories? Does it show genuine thought and effort?

4. Relevance to LS Reborn (0-100): How well does the content fit the Los Santos/GTA V universe? Does it reference appropriate locations, understand the setting, and show knowledge of roleplay?

Return ONLY a valid JSON object with these exact keys:
{
  "aiProbability": <number>,
  "quality": <number>,
  "uniqueness": <number>,
  "relevance": <number>
}

Do not include any other text, explanation, or markdown formatting. Only the JSON object.`;

// Middleware to check if the user is staff or admin
const isStaff = (req, res, next) => {
    if (req.user && (req.user.isStaff || req.user.isAdmin)) {
        return next();
    }
    return res.status(403).json({ message: 'Forbidden: Staff access required' });
};

/**
 * POST /api/analyze-text
 * Analyzes roleplay application text using Gemini AI
 * @body {string} text - The application text to analyze
 * @returns {Object} Analysis results with AI probability, quality, uniqueness, relevance scores, and plagiarism check
 */
router.post('/analyze-text', isAuthenticated, isStaff, async (req, res) => {
    const { text } = req.body;

    // Validate input
    if (!text || typeof text !== 'string') {
        return res.status(400).json({
            message: 'Text is required for analysis.',
            error: 'INVALID_INPUT'
        });
    }

    if (text.trim().length < 50) {
        return res.status(400).json({
            message: 'Text is too short for meaningful analysis (minimum 50 characters).',
            error: 'TEXT_TOO_SHORT'
        });
    }

    // Check if API key is configured
    if (!process.env.GEMINI_API_KEY) {
        console.error('GEMINI_API_KEY is not configured in environment variables');
        return res.status(500).json({
            message: 'AI Analysis service is not configured.',
            error: 'SERVICE_NOT_CONFIGURED'
        });
    }

    // --- STEP 1: Plagiarism Check (Vector Similarity) ---
    let plagiarismResult = {
        isPlagiarized: false,
        maxScore: 0,
        matches: []
    };

    // Only run plagiarism check if Pinecone is configured
    if (process.env.PINECONE_API_KEY) {
        try {
            plagiarismResult = await checkPlagiarism(text, PLAGIARISM_THRESHOLD);
            console.log(`Plagiarism check: score=${plagiarismResult.maxScore}, isPlagiarized=${plagiarismResult.isPlagiarized}`);
        } catch (plagiarismError) {
            console.error('Plagiarism check error (non-blocking):', plagiarismError.message);
            // Continue with analysis even if plagiarism check fails
        }
    }

    // --- STEP 2: AI Analysis ---
    try {
        // Initialize the Gemini model
        const model = genAI.getGenerativeModel({
            model: 'gemini-1.5-flash',
            generationConfig: {
                temperature: 0.3, // Lower temperature for more consistent analysis
                topP: 0.8,
                topK: 40,
                maxOutputTokens: 256, // We only need a small JSON response
            }
        });

        // Construct the prompt
        const prompt = `${SYSTEM_INSTRUCTION}\n\n---\n\nApplication Text to Analyze:\n\n${text}`;

        // Generate content using Gemini
        const result = await model.generateContent(prompt);
        const response = await result.response;
        const responseText = response.text();

        // Parse the JSON response
        let analysisResult;
        try {
            // Clean the response text (remove any markdown code blocks if present)
            let cleanedResponse = responseText.trim();
            if (cleanedResponse.startsWith('```json')) {
                cleanedResponse = cleanedResponse.replace(/^```json\s*/, '').replace(/\s*```$/, '');
            } else if (cleanedResponse.startsWith('```')) {
                cleanedResponse = cleanedResponse.replace(/^```\s*/, '').replace(/\s*```$/, '');
            }

            analysisResult = JSON.parse(cleanedResponse);
        } catch (parseError) {
            console.error('Failed to parse Gemini response:', responseText);
            return res.status(500).json({
                message: 'Failed to parse AI response. Please try again.',
                error: 'PARSE_ERROR',
                rawResponse: responseText
            });
        }

        // Validate the response structure
        const requiredKeys = ['aiProbability', 'quality', 'uniqueness', 'relevance'];
        const missingKeys = requiredKeys.filter(key => !(key in analysisResult));

        if (missingKeys.length > 0) {
            console.error('Invalid Gemini response structure:', analysisResult);
            return res.status(500).json({
                message: 'AI returned an incomplete response. Please try again.',
                error: 'INCOMPLETE_RESPONSE',
                missingKeys
            });
        }

        // Ensure all values are within valid range (0-100)
        for (const key of requiredKeys) {
            const value = analysisResult[key];
            if (typeof value !== 'number' || value < 0 || value > 100) {
                analysisResult[key] = Math.max(0, Math.min(100, Number(value) || 0));
            }
        }

        // Return the analysis results with plagiarism data
        res.json({
            success: true,
            analysis: {
                aiProbability: Math.round(analysisResult.aiProbability),
                quality: Math.round(analysisResult.quality),
                uniqueness: Math.round(analysisResult.uniqueness),
                relevance: Math.round(analysisResult.relevance)
            },
            plagiarism: {
                isPlagiarized: plagiarismResult.isPlagiarized,
                similarityScore: plagiarismResult.maxScore,
                matchedRules: plagiarismResult.matches || []
            },
            analyzedAt: new Date().toISOString()
        });

    } catch (error) {
        console.error('Gemini API Error:', error);

        // Handle specific error types
        if (error.message?.includes('QUOTA_EXCEEDED') || error.message?.includes('429')) {
            return res.status(429).json({
                message: 'AI service is temporarily busy. Please try again in a few moments.',
                error: 'RATE_LIMITED'
            });
        }

        if (error.message?.includes('API_KEY_INVALID') || error.message?.includes('401')) {
            return res.status(500).json({
                message: 'AI service authentication failed.',
                error: 'AUTH_FAILED'
            });
        }

        if (error.message?.includes('SAFETY') || error.message?.includes('blocked')) {
            return res.status(400).json({
                message: 'The text could not be analyzed due to content restrictions.',
                error: 'CONTENT_BLOCKED'
            });
        }

        // Generic error fallback
        return res.status(500).json({
            message: 'An error occurred while analyzing the text. Please try again.',
            error: 'INTERNAL_ERROR',
            details: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});

module.exports = router;
